config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions" }
  root 'home#index'
  resources :organizations
  resources :users
  resources :pay_slips
  resources :user_pay_slips do
    get 'user_payslips', on: :collection
  end

end

app/models/user_pay_slip.rb
class UserPaySlip < ActiveRecord::Base
  belongs_to :user
  belongs_to :pay_slip
  validates_associated :user, :pay_slip
  validates_presence_of :pay_month
  validates_presence_of :amount

  validates :pay_year, presence: true
  validate :validate_pay_year_month

  validates :pay_slip, uniqueness: { scope: [:user, :pay_month, :pay_month] }

  private

  def validate_pay_year_month
    if user.date_of_join.strftime("%Y").to_i > pay_year
      self.errors.add(:pay_month, "Please provide valid year, Check join year")
    elsif user.date_of_join.strftime("%Y").to_i == pay_year && user.date_of_join.strftime("%m").to_i > pay_year
      self.errors.add(:pay_month, "Please provide valid month, Check join month")
    end
  end
end

app/controllers/user_pay_slips_controller.rb
class UserPaySlipsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @user = @current_organization.users.where(id: params[:user_id]).first
    @user_pay_slip = @user.user_pay_slips.new if @user.present?
  end

  def create
    @user_pay_slip = UserPaySlip.create(user_pay_params)
  end

  def user_payslips
    @user_id = params[:user_id]
    @user_pay_slips = UserPaySlip.where(user_id: @user_id)
  end

  private

  def user_pay_params
    params.permit(:amount, :pay_slip_id, :pay_month, :pay_year, :user_id)
  end

end

app/helpers/user_pay_slip_helper.rb
module UserPaySlipHelper
  def user_payslip_years
    @user_pay_slips.group_by{|e| [e.pay_year]}
  end

  def months
    { :JAN => 1, :FEB => 2, :MAR => 3, :APR => 4, :MAY => 5, :JUN => 6, :JUL => 7, :AUG => 8, :SEP => 9, :OCT => 10, :NOV => 11, :DEC => 12 }
  end
end

app/views/user_pay_slips/_form.html.haml
.row.user-pay-slip-content
  .col-md-3
    .form-group.label-floating.pay_year
      %label.control-label Year
      = select_year Date.today, { :start_year => Date.current.year, :end_year => @current_organization.estb_date.strftime("%Y").to_i }, { :class => 'form-control' }
  .col-md-3
    .form-group.label-floating.pay_month
      %label.control-label Month
      = select_month(Date.today, {}, { :class => 'form-control' })
.row.user-pay-slip-content
  - @current_organization.pay_slips.each do |pay_slip|
    = form_tag user_pay_slips_path, method: :POST, remote: true do
      .row{ style: 'display: flex;align-items: center;' }
        .col-md-2
          %a.pay-type
            - if pay_slip.pay_type == true
              %i.fa.fa-2x.fa-toggle-on
            - else
              %i.fa.fa-2x.fa-toggle-off
        .col-md-8
          .form-group.label-floating.name
            %label.control-label
              = pay_slip.name
            %input.form-control{ type: 'text', name: 'amount' }
            %input{ type: 'hidden', name: 'pay_slip_id', value: pay_slip.id }
            %input.pay-month{ type: 'hidden', name: 'pay_month', value: Date.current.month }
            %input.pay-year{ type: 'hidden', name: 'pay_year', value: Date.current.year }
            %input{ type: 'hidden', name: 'user_id', value: @user.id }
        .col-md-2
          %button.btn.btn-primary.btn-round.btn-just-icon
            %i.material-icons done

:javascript

  $('.user-pay-slip-content').on('change', '#date_year', function(){
    $('.user-pay-slip-content .pay-year').val($(this).val());
  });

  $('.user-pay-slip-content').on('change', '#date_month', function(){
    $('.user-pay-slip-content .pay-month').val($(this).val());
  });

app/views/user_pay_slips/_index.html.haml
.content
  .container-fluid
    .row
      .col-md-12
        .card
          .card-content.table-responsive
            %table.table
              %thead.text-primary
                %th Name
                %th Date of Join
                %th Designation
                %th Contact
                %th
              %tbody
                - @current_organization.users.each do |user|
                  %tr
                    %td
                      = user.name
                    %td
                      = user.date_of_join.strftime("%b %d, %Y")
                    %td
                      = user.designation
                    %td
                      = user.contact
                    %td
                      %a{ href: new_user_pay_slip_path(user_id: user.id), 'data-remote': true }
                        %i.material-icons open_in_new
                      %a{ href: user_payslips_user_pay_slips_path(user_id: user.id), 'data-remote': true }
                        %i.material-icons event_note

app/views/user_pay_slips/_months_list.html.haml
.content
  .container-fluid
    .row
      - months.each do |month|
        .col-md-2
          %a.btn.btn-primary{:href => "#"}
            = month

app/views/user_pay_slips/_user_payslips.html.haml
.content
  .container-fluid
    .row
      .col-md-8
        .card
          .card-content
            - user_payslip_years.keys.each do |year|
              .col-md-4
                %button.btn.btn-primary.btn-year{ value: year.first, 'data-user': @user_id }
                  = year.first

:javascript
  $(function () {
    $('.btn-year').on('click', function(){
      var year = $(this).val();
      var userId = $(this).data("user");
      $("#myModal .modal-body").html("#{ j render 'user_pay_slips/months_list', year: year, user_id: userId }");
      showModel("PaySlip Generation");
    });
  });
-# .col-md-4
-#   .card.card-profile
-#     .card-avatar
-#       %a{:href => "#pablo"}
-#         %img.img{:src => ""}/
-#     .content
-#       %h6.category.text-gray CEO / Co-Founder
-#       %h4.card-title Alec Thompson
-#       %p.card-content
-#         Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
-#       %a.btn.btn-primary.btn-round{:href => "#pablo"} Follow

app/views/user_pay_slips/create.js.erb
<% if @user_pay_slip.errors.present? %>
  showNotification("warning", "<%= @user_pay_slip.errors.full_messages.first %>");
<% else %>
  showNotification("success", "PaySlip Element Successfully Created");
<% end %>

app/views/user_pay_slips/index.js.erb
var userContent = $(".admin-container .user-content");
userContent.html("<%= j render 'user_pay_slips/index' %>");

app/views/user_pay_slips/new.js.erb
<% if @user.present? %>
  <% if @user_pay_slip.present? %>
    $("#myModal .modal-body").html("<%= j render 'user_pay_slips/form' %>");
    showModel("<%= @user.name %> PaySlip Generation");
  <% end %>
<% else %>
  showNotification("warning", "Wrong user details!!!");
<% end %>

app/views/user_pay_slips/user_payslips.js.erb
<% if @user_pay_slips.present? %>
  var userContent = $(".admin-container .user-content");
  userContent.html("<%= j render 'user_pay_slips/user_payslips' %>");
<% end %>