config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions" }
  root 'home#index'
  resources :organizations
  resources :users
  resources :pay_slips
  resources :user_pay_slips do
    get 'user_payslips', on: :collection
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  include Organizations

  def index
    if current_user.role == 'super_admin'
      @layout = 'super_admin'
      @organizations = get_organizations
    elsif current_user.role == 'admin'
      @layout = 'admin'
    end
  end

end

app/views/home/_index_admin.html.haml
.content
  .container-fluid.admin-container
    .row.user-content
      .col-lg-3.col-md-6.col-sm-6
        .card.card-stats
          .card-header{"data-background-color" => "blue"}
            %a{ href: "#{new_user_path(id: @current_organization.id)}", data: { remote: true, method: :get } }
              %i.material-icons person_add
          .card-content
            %a{ href: "#{users_path}", data: { remote: true, method: :get } }
              %p.category Users
              %h3.title.org-count
                = @current_organization.users.count
      .col-lg-3.col-md-6.col-sm-6
        .card.card-stats
          .card-header{"data-background-color" => "green"}
            %a{ href: "#{new_user_path(id: @current_organization.id)}", data: { remote: true, method: :get } }
              %i.material-icons person_add
          .card-content
            %a{ href: "#{pay_slips_path}", data: { remote: true, method: :get } }
              %p.category Pay Slips Elements
              %h3.title.org-count
                = @current_organization.pay_slips.count

app/views/home/_index_superadmin.html.haml
.content
  .container-fluid
    .row
      .col-lg-3.col-md-6.col-sm-6
        .card.card-stats
          %a{ href: "#{organizations_path}"  }
            .card-header{"data-background-color" => "orange"}
              %i.material-icons domain
          .card-content
            %a{ href: "#{organizations_path}" }
              %p.category Organizations
              %h3.title.org-count
                = @organizations.size
          .card-footer
            .stats
              %i.material-icons.text-danger domain
              %a{:href => "#{new_organization_path}"} Add organization

app/views/home/index.html.haml
- if current_user.role == 'super_admin'
  = render 'home/index_superadmin'
- elsif current_user.role == 'admin'
  = render 'home/index_admin'