config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions" }
  root 'home#index'
  resources :organizations
  resources :users
  resources :pay_slips
  resources :user_pay_slips do
    get 'user_payslips', on: :collection
  end

end

app/models/pay_slip.rb
class PaySlip < ActiveRecord::Base
  has_many :user_pay_slips
  belongs_to :organization
  before_validation :strip_content

  validates_presence_of :name
  validates_uniqueness_of :name, scope: :organization
  validates :percent, :allow_blank => true, numericality: { only_integer: true }

  private

  def strip_content
    self.name = self.name.strip unless self.name.nil?
  end
end

app/controllers/pay_slips_controller.rb
class PaySlipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pay_slip_element = org_pay_slips.new
  end

  def new
    # @organization = get_organization(params[:id])
    # @user = User.new
  end

  def create
    @pay_slip = org_pay_slips.new(payslip_params)
    @pay_slip.save
  end

  def edit
    @pay_slip_element = org_pay_slips.where(id: params[:id]).first
  end

  def update
    @pay_slip_element = org_pay_slips.where(id: params[:id]).first
    @pay_slip_element.update_attributes(payslip_params) if @pay_slip_element.present?
  end

  private

  def org_pay_slips
    @current_organization.pay_slips
  end

  def payslip_params
    params.require(:pay_slip).permit(:name, :percent, :pay_type, :remark)
  end

end

app/views/pay_slips/_form.html.haml
.pay-form-container
  = form_for @pay_slip_element, html: {multipart: :true}, remote: true, authenticity_token: true do |f|
    .row{ style: 'display: flex;align-items: center;justify-content: space-between;' }
      .col-md-4{ style: 'display: flex;align-items: center;justify-content: space-between;' }
        .col-md-2
          %a.pay-type
            - if @pay_slip_element.pay_type == true
              %i.fa.fa-2x.fa-toggle-on
            - else
              %i.fa.fa-2x.fa-toggle-off
            = f.hidden_field :pay_type, class: 'form-control ptype'
        .col-md-10
          .form-group.label-floating.name
            %label.control-label Element
            = f.text_field :name, class: 'form-control'
      .col-md-6{ style: 'display: flex;align-items: center;justify-content: space-between;' }
        .col-md-2
          .form-group.label-floating.percent
            %label.control-label Percent
            = f.text_field :percent, class: 'form-control'
        .col-md-10
          .form-group.label-floating.remark
            %label.control-label Remark
            = f.text_field :remark, class: 'form-control'
      .col-md-2
        %button.btn.btn-white.btn-round.btn-just-icon{ type: 'submit' }
          %i.material-icons done

:scss
  .pay-form-container{
    .control-label{
      color: #4a148c !important;
    }
    .btn-white-circle{
      border-radius: 50%;
      border: 1px solid red;
      background-color: #fff;
      color: #aaa;
    }
  }

:javascript
  $(function(){
    $('.pay-form-container').on('click', '.pay-type', function(){
      payType = $(this).find('.ptype').val();
      if(payType == 'false'){
        $(this).find('.ptype').val(true);
        $(this).find('.fa').toggleClass('fa-toggle-on fa-toggle-off');
      }else{
        $(this).find('.ptype').val(false);
        $(this).find('.fa').toggleClass('fa-toggle-off fa-toggle-on');
      }
    });
  });

app/views/pay_slips/_index.html.haml
.content
  .container-fluid
    .row
      .col-md-12
        .card
          .card-header{ 'data-background-color' => 'blue' }
            %h4.title Pay Slip
            %p.category.payslip-new-form
              = render 'pay_slips/form'
          .card-content.table-responsive.payslip-container
            = render 'pay_slips/payslip_elements', pay_slips: @current_organization.pay_slips.reload

app/views/pay_slips/_payslip_elements.html.haml
%table.table
  %thead.text-primary
    %th Name
    %th Pay Type
    %th Remarks
    %th percent
    %th
  %tbody
    - if pay_slips.count > 0
      - pay_slips.each do |pay_slip|
        %tr
          %td
            = pay_slip.name
          %td
            = pay_slip.pay_type == true ? "Earnings" : "Deductions"
          %td
            = pay_slip.remark
          %td
            = pay_slip.percent
          %td
            %a{ href: "#{edit_pay_slip_path(pay_slip.id)}", 'data-remote': true  }
              %i.material-icons border_color
            %a{ href: "#{pay_slip_path(pay_slip.id)}" }
              %i.material-icons delete
    - else
      %tr
        %td
          = "No payslip elements present yet!!!"

app/views/pay_slips/create.js.erb
<% if @pay_slip.errors.present? %>
  <% @pay_slip.errors.messages.each do |key, value| %>
    $('.<%= key.to_s %>').addClass('has-error');
    $('.<%= key.to_s %>').append("<div class='text-danger'><%= key %> <%= value[0] %></div>");
  <% end %>
<% else %>
  showNotification("success", "Successfully created");
  $('.payslip-container').html("<%= j render 'pay_slips/payslip_elements', pay_slips: @current_organization.pay_slips.reload %>");
<% end %>

app/views/pay_slips/edit.js.erb
<% if @pay_slip_element.present? %>
  $("#myModal .modal-body").addClass('payslip-edit-form');
  $("#myModal .modal-body").html("<%= j render 'pay_slips/form' %>");
  showModel('PaySlip element');
<% else %>
  showNotification("warning", "PaySlip element not found!!!");
<% end %>

app/views/pay_slips/index.js.erb
var userContent = $(".admin-container .user-content");
userContent.html("<%= j render 'pay_slips/index' %>");

app/views/pay_slips/update.js.erb
<% if @pay_slip_element.present? %>
  <% if @pay_slip_element.errors.present? %>
    <% @pay_slip_element.errors.messages.each do |key, value| %>
      $('.payslip-edit-form .<%= key.to_s %>').addClass('has-error');
      $('.payslip-edit-form .<%= key.to_s %>').append("<div class='text-danger'><%= key %> <%= value[0] %></div>");
    <% end %>
  <% else %>
    hideModel();
    showNotification("success", "Successflly updated");
    $('.payslip-container').html("<%= j render 'pay_slips/payslip_elements', pay_slips: @current_organization.pay_slips.reload %>");
  <% end %>
<% else %>
  showNotification("warning", "PaySlip element not found!!!");
<% end %>