config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions" }
  root 'home#index'
  resources :organizations
  resources :users
  resources :pay_slips
  resources :user_pay_slips do
    get 'user_payslips', on: :collection
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  before_validation :strip_content

  has_many :addresses
  accepts_nested_attributes_for :addresses, allow_destroy: true
  has_many :users
  accepts_nested_attributes_for :users, allow_destroy: true
  has_many :pay_slips
  validates_presence_of :name
  validates_presence_of :estb_date
  validates_presence_of :description
  validates_presence_of :domain
  validates_uniqueness_of :domain

  private
    def strip_content
      self.name = self.name.strip unless self.name.nil?
      self.domain = self.domain.strip unless self.domain.nil?
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!
  layout 'super_admin', only: %i(index new create show)
  include Organizations

  def index
    @organizations = get_organizations
    authorize @organizations
  end

  def new
    @organization = Organization.new
    authorize @organization
  end

  def create
    org_name = params[:organization][:name] || ""
    @organization = Organization.where(name: org_name.strip).first
    if @organization.blank?
      @organization = Organization.new(organization_params)
      authorize @organization
      @organization.save
    else
      @organization.errors.add(:name, "already existed")
    end
  end

  def show
    @organization = get_organization(params[:id])
    authorize @organization
  end

  def update
    @organization = Organization.where(id: params[:id]).first
    authorize @organization
    @organization.update_attributes(organization_params)
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :estb_date, :domain, :description,
      addresses_attributes: [:id, :street_address1, :street_address2, :city, :state, :postal_code, :country])
  end
end

app/views/organizations/_details.html.haml
.col-lg-12.col-md-12
  .card
    .card-content.table-responsive
      = render 'organizations/form', organization: organization

app/views/organizations/_devise_flash_messages.html.haml
- flash.each do |key, value|
  - if black_list_alerts.exclude? value
    %div.text-warning{ class: "alert-msg alert-#{ key  }"  }
      %a{ href:'#', 'data-dismiss': :"alert-#{ key  }", class: 'close'  }
        &times;
      = "#{value}"

app/views/organizations/_form.html.haml
= form_for organization, html: {multipart: :true}, remote: true, authenticity_token: true do |f|
  .row
    .col-md-5
      .form-group.label-floating.name
        %label.control-label Organization
        = f.text_field :name, class: 'form-control'
    .col-md-4
      .form-group.label-floating.estb_date
        %label.control-label Estb Date(mm/dd/YYYY)
        = f.text_field :estb_date, class: 'form-control datepicker', id: 'datepicker', value: "#{organization.estb_date.strftime('%d/%m/%Y') if organization.estb_date.present? }"
    .col-md-3
      .form-group.label-floating.domain
        %label.control-label Domain
        = f.text_field :domain, class: 'form-control'
  .row
    .col-md-12
      .form-group
        %label Desciption
        .form-group.label-floating.description
          %label.control-label Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.
          = text_area :organization, :description, class: 'form-control', rows: '5'
  %label Address:
  = f.fields_for :addresses, action_name == 'new' || organization.addresses.blank? ? Address.new : nil do |addresses_form|
    .row
      .col-md-4
        .form-group.label-floating.street_address1
          %label.control-label Street Address1
          = addresses_form.text_field :street_address1, class: 'form-control'
      .col-md-4
        .form-group.label-floating.street_address2
          %label.control-label Street Address2
          = addresses_form.text_field :street_address2, class: 'form-control'
      .col-md-4
        .form-group.label-floating.city
          %label.control-label City
          = addresses_form.text_field :city, class: 'form-control'
    .row
      .col-md-4
        .form-group.label-floating.state
          %label.control-label State
          = addresses_form.text_field :state, class: 'form-control'
      .col-md-4
        .form-group.label-floating.postal_code
          %label.control-label Postal Code
          = addresses_form.text_field :postal_code, class: 'form-control'
      .col-md-4
        .form-group.label-floating.country
          %label.control-label Country
          = addresses_form.text_field :country, class: 'form-control'

  = f.submit :Create, class: 'btn btn-primary pull-right'

:javascript
  $( function() {
    $('.datepicker').datepicker()
      .on('changeDate', function(ev){
        $(this).parent('.label-floating').removeClass('is-empty');
        $(this).parent('.label-floating').removeClass('has-error');
    });
  });

app/views/organizations/_settings.html.haml
settings

app/views/organizations/_users.html.haml
.col-lg-12.col-md-12.col-sm-12.users-container
  .card.card-stats
    .card-header{"data-background-color" => "blue"}
      %a{ href: "#{new_user_path(id: organization.id)}", data: { remote: true, method: :get } }
        %i.material-icons person_add
    .card-content
      %p.category Used Space
      %h3.title
        49/50
        %small GB
    .stats
      = render "users/users", users: organization.users

:scss
  .users-container{
    .stats{
      margin: 10px;
    }
  }

app/views/organizations/create.js.erb
$('.new_organization .row').each(function(){
  $(this).find('.form-group').each(function(){
    $(this).find('.text-danger').html('');
    $(this).removeClass('.has-error');
  });
});
<% if @organization.errors.present? %>
  <% @organization.errors.messages.each do |key, value| %>
    $('.<%= key.to_s %>').addClass('has-error');
    $('.<%= key.to_s %>').append("<div class='text-danger'><%= key %> <%= value[0] %></div>");
  <% end %>
  <% if @organization.addresses.present? && @organization.addresses.first.errors.present? %>
    <% @organization.addresses.first.errors.messages.each do |key, value| %>
      $('.<%= key.to_s %>').addClass('has-error');
      $('.<%= key.to_s %>').append("<div class='text-danger'><%= key %> <%= value[0] %></div>");
    <% end %>
  <% end %>
<% else %>
    showNotification("success", "Successfully created");
<% end %>

app/views/organizations/index.html.haml
.content
  .container-fluid
    .row
      .col-md-12
        .card
          .card-header{ 'data-background-color' => 'purple' }
            %h4.title Organizations
            %p.category Organizations List
          .card-content.table-responsive
            %table.table
              %thead.text-primary
                %th Name
                %th Established Date
                %th Domain
                %th Employees
                %th
              %tbody
                - @organizations.each do |organization|
                  %tr
                    %td
                      = organization.name
                    %td
                      = organization.estb_date
                    %td
                      = organization.domain
                    %td
                      = organization.users_count
                    %td
                      %a.btn.btn-primary{ href: "#{organization_path(organization.id)}" }
                        = 'Check'

app/views/organizations/new.html.haml
.content
  .container-fluid
    .row
      .col-md-12
        .card
          .card-header{"data-background-color" => "purple"}
            %h4.title Add Organization
            %p.category Complete organization profile
          .card-content
            = render 'organizations/form', organization: @organization

app/views/organizations/show.html.haml
.row.org-content
  .col-lg-12.col-md-12
    .card.card-nav-tabs
      .card-header{"data-background-color" => "purple"}
        .nav-tabs-navigation
          .nav-tabs-wrapper
            %span.nav-tabs-title
              = "#{@organization.domain} :"
            %ul.nav.nav-tabs{"data-tabs" => "tabs"}
              %li.active
                %a{"data-toggle" => "tab", :href => "#details"}
                  %i.material-icons bug_report
                  Bugs
                  .ripple-container
              %li
                %a{"data-toggle" => "tab", :href => "#users"}
                  %i.material-icons code
                  Website
                  .ripple-container
              %li
                %a{"data-toggle" => "tab", :href => "#settings"}
                  %i.material-icons cloud
                  Server
                  .ripple-container
      .card-content
        .tab-content
          #details.tab-pane.active
            = render 'organizations/details', organization: @organization
          #users.tab-pane
            = render 'organizations/users', organization: @organization
          #settings.tab-pane
            = render 'organizations/settings', organization: @organization

app/views/organizations/update.js.erb
$('.edit_organization .row').each(function(){
  $(this).find('.form-group').each(function(){
    $(this).find('.text-danger').html('');
    $(this).removeClass('has-error');
  });
});
<% if @organization.errors.present? %>
  <% @organization.errors.messages.each do |key, value| %>
    $('.<%= key.to_s %>').addClass('has-error');
    $('.<%= key.to_s %>').append("<div class='text-danger'><%= key %> <%= value[0] %></div>");
  <% end %>
  <% if @organization.addresses.present? && @organization.addresses.first.errors.present? %>
    <% @organization.addresses.first.errors.messages.each do |key, value| %>
      $('.<%= key.to_s %>').addClass('has-error');
      $('.<%= key.to_s %>').append("<div class='text-danger'><%= key %> <%= value[0] %></div>");
    <% end %>
  <% end %>
<% else %>
    showNotification("success", "Successfully created");
<% end %>